In [ ]:
# split this string

In [1]:
s = "Hi there Sam"

x = s.split()

print(x)

['Hi', 'there', 'Sam']


In [ ]:
use.format() to print the following string.
output should be:The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


In [ ]:
in this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


In [ ]:
create an array of 10 zero

In [7]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
create an array of 10 fives

In [9]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 30 to 70")
print(array) 


Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


In [11]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
concatinate a and b
a=np.array([1,2,3]),b=np.array([4,5,6])

In [12]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]


In [ ]:
pandas

In [ ]:
create a data frame with 3 rows and 2 columns

In [14]:
import pandas as pd
data = {'Name': ['Tom', 'nick', 'jack'],
        'Age': [20, 21, 18]}
df = pd.DataFrame(data)
df

Name  Age
0   Tom   20
1  nick   21
2  jack   18

In [ ]:
generate the series of dates from 1st jan,2023 to 10th feb,2023

In [26]:
import pandas as pd
  
per1 = pd.date_range(start ='01-01-2023', 
         end ='02-10-2023')
  
for val in per1:
    print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


In [ ]:
create 2D list to dataframe
lists=[[1 , 'aaa' , 22],[2, 'bbb' , 25],[3,'ccc',24]]

In [49]:
import pandas as pd  
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]     
df = pd.DataFrame(lists, columns =['s.no','name','age']) 
print(df)

   s.no name  age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
